server:
  port: 8080
spring:
  rabbitmq:
    #用户名
    username: XXX
    #密码
    password: XXX
    #vhost
    virtual-host: /admin_vhost
    #rabbitmq服务IP
    host: 49.XXX.XXX.XXX
    #rabbitmq端口号
    port: 5672
    publisher-confirm-type: correlated

#交换机
exhange:
  name: fanout_exchange_yonyou
#队列
queueName:
  name: fanout_queue_yonyou
